Build executables
Equanox/gotron pull request #4
Opened 2018-09-19 20:18 UTC by puengel

Tested with Windows and Ubuntu.

2018-09-19 20:19 UTC, puengel commented on app/package.json
> -    "electron": "latest",
Required by electron builder.

2018-09-19 20:20 UTC, puengel commented on package.json
> +    "go": "go build && gotron",
Only works for windows. Windows cmd cannot hanlde "./gotron" call

2018-09-20 20:02 UTC, Equanox requested changes

2018-09-20 20:02 UTC, Equanox commented on package.json
> +    "dist:linux": "build -l && cross-env-shell GOOS=windows GOARCH=amd64 go build -tags prod",
GOOS=linux

2018-09-24 15:15 UTC, Equanox approved these changes

2018-09-24 15:18 UTC, merged